# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: jsd23
# "service" is the name of this project. This will also be added to your AWS resource names.
service: quiztopia

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
  role: arn:aws:iam::440744238402:role/firstRole
  environment:
    SECRET: hej

functions:
  getQuizes:
    handler: services/api/getQuizes.handler
    events:
      - httpApi:
          path: /quiz
          method: get

  postQuiz:
    handler: services/api/postQuiz.handler
    events:
      - httpApi:
          path: /quiz
          method: post

  postQuestion:
    handler: services/api/postQuestion.handler
    events:
      - httpApi:
          path: /quiz/question
          method: post

  getSpecificQuiz:
    handler: services/api/getSpecificQuiz.handler
    events:
      - httpApi:
          path: /quiz/{quizId}
          method: get

  deleteQuiz:
    handler: services/api/deleteQuiz.handler
    events:
      - httpApi:
          path: /quiz/{quizId}
          method: delete

  signup:
    handler: services/auth/signup.handler
    events:
      - httpApi:
          path: /auth/signup
          method: post

  login:
    handler: services/auth/login.handler
    events:
      - httpApi:
          path: /auth/login
          method: post

  registerHighscore:
    handler: services/api/registerHighscore.handler
    events:
      - httpApi:
          path: /quiz/register
          method: post


  getHighscore:
    handler: services/api/getHighscore.handler
    events:
      - httpApi:
          path: /quiz/highscore
          method: get

resources:
  Resources:
    quizes:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: quizes
        AttributeDefinitions:
          - AttributeName: quizType
            AttributeType: S  
          - AttributeName: quizId
            AttributeType: S  
          - AttributeName: quizname
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: quizType
            KeyType: HASH  
          - AttributeName: quizId
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: QuizNameUserIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH  
              - AttributeName: quizname
                KeyType: RANGE  
            Projection:
              ProjectionType: ALL  
        BillingMode: PAY_PER_REQUEST

    users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S 
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    leaderboard:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: leaderboard
        AttributeDefinitions:
          - AttributeName: quizId
            AttributeType: S
          - AttributeName: highscore
            AttributeType: N
        KeySchema:
          - AttributeName: quizId
            KeyType: HASH
          - AttributeName: highscore
            KeyType: RANGE

        BillingMode: PAY_PER_REQUEST